# FAISS Vector Retrieval Example

In this notebook, we will demonstrate how to use FAISS to load 10 vectors and perform a nearest neighbor search.

In [1]:
# Import necessary libraries
import numpy as np
import faiss

In [2]:
# Generate 10 random vectors of dimension 128
dim = 128  # Dimension of each vector
num_vectors = 10  # Number of vectors
vectors = np.random.random((num_vectors, dim)).astype('float32')

print("Generated vectors:")
print(vectors)

Generated vectors:
[[0.50288385 0.51864064 0.5485412  ... 0.8836286  0.7422972  0.1313188 ]
 [0.78990406 0.10816219 0.15899388 ... 0.883774   0.10300164 0.5819386 ]
 [0.13159418 0.5759136  0.70206314 ... 0.32314888 0.5041634  0.46005592]
 ...
 [0.52426094 0.55352765 0.00466931 ... 0.92873037 0.16490874 0.37204826]
 [0.9968076  0.7479123  0.17953645 ... 0.104969   0.25944975 0.98043114]
 [0.9331861  0.755035   0.71320295 ... 0.5145971  0.83130616 0.2699537 ]]


In [3]:
# Create a FAISS index
index = faiss.IndexFlatL2(dim)  # L2 distance index

# Add vectors to the index
index.add(vectors)
print(f"Number of vectors in the index: {index.ntotal}")

Number of vectors in the index: 10


In [4]:
# Perform a nearest neighbor search
query_vector = np.random.random((1, dim)).astype('float32')  # Generate a random query vector
k = 3  # Number of nearest neighbors to retrieve

print("Query vector:")
print(query_vector)

D, I = index.search(query_vector, k)  # D: distances, I: indices

print("Indices of nearest neighbors:", I)
print("Distances to nearest neighbors:", D)

Query vector:
[[5.9157187e-01 8.9375830e-01 7.8404099e-01 1.0267660e-01 1.6475289e-01
  1.5841693e-01 8.9872479e-01 5.2519149e-01 9.1015190e-01 8.3807790e-01
  2.7130330e-01 7.5783253e-01 4.5194450e-01 5.6189779e-02 3.8061026e-02
  1.6615617e-01 7.3562485e-01 3.5293806e-01 4.2982388e-01 5.5968213e-01
  7.5942165e-01 4.5872188e-01 9.7210455e-01 2.2685187e-01 4.3720710e-01
  9.2679393e-01 4.8297131e-01 6.3242722e-01 8.6535400e-01 2.4239214e-01
  7.7143896e-01 3.0678076e-01 6.6439152e-01 3.4160006e-01 4.3696329e-01
  9.7890973e-01 4.7633460e-01 1.6550995e-01 5.6283820e-01 8.4839213e-01
  4.2336878e-01 1.3340880e-01 1.5632407e-01 3.7515387e-01 9.5890290e-01
  6.6446178e-03 3.8354132e-01 8.0941719e-01 8.9058876e-01 1.1791518e-01
  2.6621512e-01 1.3243467e-01 4.0999413e-01 9.8644122e-03 9.7433984e-01
  3.7738907e-01 1.3563685e-01 1.7211553e-01 3.7324494e-01 6.4333403e-01
  6.4021456e-01 7.5230002e-01 7.0033181e-01 7.0106244e-01 6.2505364e-01
  3.8534734e-01 4.6675935e-01 1.4298221e-01 6.5114